# CircleCIの設定ファイルのフォーマット指定
# (2 or 2.1 を選択)
version: 2.1

jobs:
  build-frontend:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:17
    steps:
      - checkout
      - run:
          name: install dependencies
          command:  npm install
      - restore_cache:
          key: animation-app-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
      - save_cache:
          key: animation-app-{{ checksum "package-lock.json" }}
          paths:
            - ~/workspace/node_modules


workflows:
  version: 2
  test-frontend:
    jobs:
      - build-frontend
