// import * as React from 'react'
import type { NextPage } from 'next'
import MainLayout from '../layouts'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
// import { Media } from "../components/media"

import React, { useState, useEffect } from 'react'
//todosのgetHelloメソッド使ってるから
import { getHello, deleteHello, updateHello } from '../lib/api/hellos'
import Type from '../types'

import Test from '../components/counter'

import TodoList from '../components/todoList'

const Home: NextPage = () => {
  // const useMedia = Media();
  // useStateでstateを設定、<Type['helloObj']>はimportされたTypeの中のhelloObjを参照
  // typescriptではid, title, textの型を設定してるので必要なデータを初期値を入れる
  const [helloData, setText] = useState<Type['helloObj']>({
    id: 0,
    title: '',
    text: '',
  })

  // FIXME:axiosの直書きここに描きたくないなーどうにかならんかな
  // データ変更用(state用)のファイル作った方がいい気がする
  // 表示とデータ更新一緒にするの怖い

  // handlegetHello関数を設定axiosでデータを取ってきてtry catchでresponseを返している
  const handlegetHello = async () => {
    try {
      const res = await getHello()
      if (res?.status === 200) {
        console.log('============ return status 200')
        // setTextでhelloDataのstateを変更、値は引数のres.data.text
        setText(res.data)
      } else {
        console.log('============ return else')
        console.log(res.data.text)
      }
    } catch (err) {
      console.log('============ catch error')
      console.log(err)
    }
  }

  const handledeleteHello = async (id: number) => {
    try {
      // これでidをparamsに持ってserverにいく
      const res = await deleteHello(id)
      if (res?.status === 200) {
        console.log('============ return status 200')
        // setTextでhelloDataのstateを変更、値は引数のres.data.text
        // 例) setTodos((prev: Todo[]) => prev.filter((todo: Todo) => todo.id !== id))
        // setText()の中にfilterを書く、なんかちょっと描き方違う？
        // ここの型指定あってる？
        const deleteHello = { id: 0, title: '', text: '' }
        setText(deleteHello)
      } else {
        console.log('============ return else')
      }
    } catch (err) {
      console.log('============ catch error')
      console.log(err)
    }
  }

  const handleupdateHello = async (data: Type['helloObj']) => {
    try {
      // これでidをparamsに持ってserverにいく
      const res = await updateHello(data)
      if (res?.status === 200) {
        console.log('============ return status 200')
        // setTextでhelloDataのstateを変更、値は引数のres.data.text
        // 例) setTodos((prev: Todo[]) => prev.filter((todo: Todo) => todo.id !== id))
        // setText()の中にfilterを書く、なんかちょっと描き方違う？
        // ここの型指定あってる？
        //
        data.title = 'こんにちはupdate!'
        const setData = {
          id: data.id,
          title: data.title,
          text: data.text,
        }
        setText(setData)
      } else {
        console.log('============ return else')
      }
    } catch (err) {
      console.log('============ catch error')
      console.log(err)
    }
  }

  // DOMの描画時(Vueでいうレンダリング)にuseEffect発火
  // useEffect発火のタイミング→さまざまなタイミングで発火できる？
  // 初回レンダリング時のみ実行する→第二引数の配列を空にして記述
  // 任意の変数が変化したときのみ実行→第二引数の配列にその変数を指定
  // ライフサイクルはVueと違うみたい
  useEffect(() => {
    handlegetHello()
  }, [])

  return (
    <MainLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          {/*
        <div>Screen is wide: {useMedia.isMobileSite ? "😃" : "😢"}</div>
  */}
          <h1>apiから送られたid:{helloData.id}</h1>
          <h1>apiから送られたtitle:{helloData.title}</h1>
          <h1>apiから送られたtext:{helloData.text}</h1>

          <Test />
          <TodoList />
          <h1>これがupdateアクションです</h1>
          <button onClick={() => handleupdateHello(helloData || {})}>
            Update
          </button>

          <h1>これがdeleteアクションです</h1>
          <button onClick={() => handledeleteHello(helloData.id || 0)}>
            Delete
          </button>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.tsx</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </MainLayout>
  )
}

export default Home
