import React from 'react'
import styles from './index.module.scss'
import Head from 'next/head'

type LayoutProps = {
  children: React.ReactNode
}

function MainLayout({ children }: LayoutProps): JSX.Element {
  return (
    <>
      <Head>
        <title>{process.env.NEXT_PUBLIC_SERVICE_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{children}</main>
    </>
  )
}

export default MainLayout
